create user 'USR_EQUIG2'@'localhost' identified by 'mpEQUIDAG2'

GRANT select ON equida18.categvente TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.cheval TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.client TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.clientcategvente TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.courriel TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.joint TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.lieu TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.lot TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.pays TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.piecejointe TO 'USR_EQUIG2'@'localhost';
GRANT select ON equida18.vente TO 'USR_EQUIG2'@'localhost';

GRANT insert ON equida18.categvente TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.cheval TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.client TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.clientcategvente TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.courriel TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.joint TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.lieu TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.lot TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.pays TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.piecejointe TO 'USR_EQUIG2'@'localhost';
GRANT insert ON equida18.vente TO 'USR_EQUIG2'@'localhost';

GRANT update ON equida18.categvente TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.cheval TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.client TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.clientcategvente TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.courriel TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.joint TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.lieu TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.lot TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.pays TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.piecejointe TO 'USR_EQUIG2'@'localhost';
GRANT update ON equida18.vente TO 'USR_EQUIG2'@'localhost';

GRANT delete ON equida18.categvente TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.cheval TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.client TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.clientcategvente TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.courriel TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.joint TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.lieu TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.lot TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.pays TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.piecejointe TO 'USR_EQUIG2'@'localhost';
GRANT delete ON equida18.vente TO 'USR_EQUIG2'@'localhost';